### ISSUE TITLE
【STL】next_permutation 算法原理 | WEIJUN LIN BLOG

### ISSUE THREAD

**Issue by Weijun-Lin** [Weijun-Lin/Personal-Blog#54]
https://joke-lin.top/2020/09/24/2020-09-24-next-permutation/#more 

 参考：
 
 【博客园】 STL next_permutation 算法原理和自行实现
 【CSDN】next_permutation和pre_permutation源码解析
 
 
 基本思路
 【STL】 next_permutation 函数就是返回当前序列的下一个字典序，已经为最大字典序则返回 False，否则为返回 True
 基本思想如下：
 
 从尾端开始依次比较两个相邻元素直到

**Comment by YeZ-Liu** [comment]
牛皮

**Comment by Colin-Jay** [comment]
#俊俏
011001100110

**Comment by Colin-Jay** [comment]
# 为啥不行

**Comment by Colin-Jay** [comment]
# 嗯？
